env:
  global:
    - PACKAGE_VERSION="$(node -p -e 'require("./package.json").version')"
language: node_js
node_js:
  - '10'
cache:
  yarn: true
  directories:
    - node_modules
    - .vscode-test
addons:
  apt:
    packages:
      - libsecret-1-dev
install:
  - yarn --frozen-lockfile --non-interactive
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
    fi
script:
  - yarn test

